### ISSUE TITLE
无法识别长消息

### ISSUE THREAD

**Issue by nzh63** [Wh1isper/qq_mem#3]
长消息中长度占两字节，如：
```
087b180: 0c e5 be ae e8 bd af e9 9b 85 e9 bb 91 12 ad 01  ................
087b190: 0a aa 01 0a a7 01 54 45 53 54 5f 4d 45 53 53 41  ......TEST_MESSA
087b1a0: 47 45 5f 4e 5a 48 32 31 5f 4c 4f 4e 47 5f 4c 4f  GE_NZH21_LONG_LO
```
相关数据为
```
ad 01 0a aa 01 0a a7 01
```

**Comment by Wh1isper** [comment]
应该可以增加判断 先尝试使用长字节 无法解码使用短字节------------------ 原始邮件 ------------------
发件人: "nzh63"<notifications@github.com>
发送时间: 2019年11月13日(星期三) 中午11:54
收件人: "Wh1isper/qq_mem"<qq_mem@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Wh1isper/qq_mem] 无法识别长消息 (#3)



长消息中长度占两字节，如：
 087b180: 0c e5 be ae e8 bd af e9 9b 85 e9 bb 91 12 ad 01  ................ 087b190: 0a aa 01 0a a7 01 54 45 53 54 5f 4d 45 53 53 41  ......TEST_MESSA 087b1a0: 47 45 5f 4e 5a 48 32 31 5f 4c 4f 4e 47 5f 4c 4f  GE_NZH21_LONG_LO  
相关数据为
 ad 01 0a aa 01 0a a7 01  
&mdash;

**Comment by nzh63** [comment]
fixed by 5ebd5c0
